### ISSUE TITLE
TypeError: url.path.test is not a function

### ISSUE THREAD

**Issue by Coolyang1996** [vusion/css-sprite-loader#11]
https://github.com/vusion/css-sprite-loader/blob/c29d3e02736a8953303bbe8110fddd25cb92ef7e/src/postcssPlugin.js#L111

**Comment by rainfore** [comment]
可以提供更多细节吗？比如 css 代码和 Webpack 配置

**Comment by Coolyang1996** [comment]
src:
```
├─index.css
├─index.js
├─static
|   ├─sprites
|   |    ├─1.png
|   |    ├─2.png
|   |    └3.png
```
webpack.config.js
```
new CSSSpritePlugin({
   padding: 5,
   filter: /static\/sprites/
})
```

**Comment by rainfore** [comment]
已经发布了，css-sprite-loader@0.3.4
多谢 PR！

**Comment by Coolyang1996** [comment]
> 已经发布了，css-sprite-loader@0.3.4
> 多谢 PR！

不客气
